# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Build documentation

on:
    workflow_dispatch:
    workflow_call:
    pull_request:
        branches:
            - main 
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
        PYTHON_VERSION: 3.10

    steps:
      # checkout the repository
      - uses: actions/checkout@v4

      # setup Python
      - name: Install Python ${PYTHON_VERSION}
        uses: actions/setup-python@v4
        with:
          python-version: ${PYTHON_VERSION}

      # preserve pip cache to speed up installation
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r dev-requirements.txt -r requirements.txt .
          python -m pip freeze

      - name: Install package
        run: python3 -m pip install .

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
            name: documentation
            path: ./docs/_build/html
            if-no-files-found: error
    